name: kelide_jazzb
description: KelideJazzb mobile application.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  states_rebuilder: ^0.1.4
  cached_network_image: ^1.1.1
  shared_preferences: ^0.5.2
  json_annotation: ^2.3.0
  http: ^0.12.0+1
  email_validator: '^1.0.0'
  flutter_bloc: 0.20.0
  hermes: ^3.0.0
  equatable: ^0.2.0
  circular_profile_avatar: ^0.1.4 #http://github.com/ch-muhammad-adil/flutter-circular_profile_avatar
  fluro: ^1.5.0
  path_provider: ^1.2.0
  event_bus: ^1.1.0
  sqflite: any
  intl: ^0.15.7
dev_dependencies:
  build_runner: ^1.4.0
  json_serializable: ^2.3.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: iranSansLight
      fonts:
        - asset: assets/fonts/iran_sans_light.ttf

    - family: iranSansBold
      fonts:
        - asset: assets/fonts/iran_sans_bold.ttf
          weight: 700

    - family: ShabnamLight
      fonts:
        - asset: assets/fonts/shabnam.ttf

    - family: ShabnamBold
      fonts:
        - asset: assets/fonts/shabnam_bold.ttf
  assets:
    - assets/images/